# Generated by Django 5.1.1 on 2024-10-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_waanverse_auth', '0003_alter_userloginactivity_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpasswordcode',
            name='attempts',
        ),
    ]
