# Generated by Django 5.1.1 on 2024-09-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('content', models.TextField()),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
