# Generated by Django 5.1.1 on 2024-09-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prerender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapedcontent',
            old_name='scraped_at',
            new_name='updated_at',
        ),
    ]
