# Generated by Django 5.1.1 on 2024-09-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prerender', '0002_rename_scraped_at_scrapedcontent_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedContent',
        ),
    ]
