# Generated by Django 5.1 on 2024-08-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_url',
        ),
    ]
