# Generated by Django 5.0.1 on 2024-03-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
