# Generated by Django 5.0.1 on 2024-03-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["-id"]},
        ),
    ]
