# Generated by Django 5.1 on 2024-09-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='google_account',
            field=models.BooleanField(default=False),
        ),
    ]
