# Generated by Django 5.1 on 2024-08-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers/'),
        ),
        migrations.AddField(
            model_name='account',
            name='cover_image_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
