# Generated by Django 5.1.1 on 2024-10-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_google_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verified_company',
            field=models.BooleanField(default=False),
        ),
    ]
