# Generated by Django 5.1 on 2024-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_cover_image_account_cover_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
