# Generated by Django 5.1 on 2024-09-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
