# Generated by Django 5.1.1 on 2024-10-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_referral_code_account_referred_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='referral_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
