# Generated by Django 5.0.1 on 2024-05-03 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="taged_accounts",
            field=models.ManyToManyField(
                blank=True, related_name="taged_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
