# Generated by Django 5.0.1 on 2024-03-10 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="last_edited",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="last_edited",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="taged_accounts",
        ),
        migrations.RemoveField(
            model_name="post",
            name="taged_accounts",
        ),
        migrations.AddField(
            model_name="comment",
            name="tagged_accounts",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_tagged", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tagged_accounts",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_tagged", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_dislikes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_dislikes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
