# Generated by Django 5.0.1 on 2024-03-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="tagged_accounts",
            new_name="taged_accounts",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="tagged_accounts",
            new_name="taged_accounts",
        ),
    ]
