# Generated by Django 5.0.1 on 2024-07-09 16:21

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_article_cover_image_alter_article_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.TextField(max_length=400),
        ),
    ]
