# Generated by Django 5.0.1 on 2024-03-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_tagged_accounts_comment_taged_accounts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentimage",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_content_images",
                to="main.comment",
            ),
        ),
        migrations.AlterField(
            model_name="contentimage",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_images",
                to="main.post",
            ),
        ),
    ]
