# Generated by Django 5.1.1 on 2024-10-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(choices=[('anger', 'Anger'), ('laughing', 'Laughing'), ('sad', 'Sad'), ('thumbs-up', 'ThumbsUp'), ('hot', 'Hot'), ('hundred', 'hundred')], max_length=50),
        ),
    ]
