# Generated by Django 5.0.1 on 2024-05-02 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_comment_dislikes_remove_comment_likes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="%(class)s_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="%(class)s_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
