# Generated by Django 5.1.1 on 2024-10-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_reaction_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
