# Generated by Django 5.1.2 on 2024-10-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_tagged_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
